
import { Station, Vehicle } from './types';

export const COLORS = {
  primary: '#22C55E',
  secondary: '#4ADE80',
  accent: '#16A34A',
  background: '#F8FAFC',
};

export const MOCK_STATIONS: Station[] = [
  {
    id: '1',
    name: 'Pulse Station',
    address: '1901 Thornridge Cir. Shiloh, Hawaii 81063',
    distance: '4.5 km',
    cost: '$15.00 / hour',
    openingHours: 'Open 24 hours',
    coordinates: { lat: 37.7749, lng: -122.4194 },
    chargers: [
      { id: 'c1', name: 'Charger A', type: 'AC type-2', capacity: '60KW', isAvailable: true },
      { id: 'c2', name: 'Charger B', type: 'CSS-2', capacity: '60KW', isAvailable: true },
    ],
    // Correcting property name from 'amenities' to 'attractions' to match Station type definition
    attractions: ['WiFi', 'Gym', 'Park', 'Parking'],
    imageUrl: 'https://picsum.photos/seed/pulse/800/400'
  },
  {
    id: '2',
    name: 'Greenspeed Station',
    address: '4140 Parker Rd. Allentown, New Mexico 31134',
    distance: '2.5 km',
    cost: '$12.00 / hour',
    openingHours: '08:00 AM - 10:00 PM',
    coordinates: { lat: 37.7849, lng: -122.4094 },
    chargers: [
      { id: 'c3', name: 'Charger A', type: 'AC type-2', capacity: '50KW', isAvailable: true },
      { id: 'c4', name: 'Charger B', type: 'DC Fast', capacity: '120KW', isAvailable: false },
    ],
    // Correcting property name from 'amenities' to 'attractions' to match Station type definition
    attractions: ['Cafe', 'WiFi', 'Parking'],
    imageUrl: 'https://picsum.photos/seed/green/800/400'
  }
];

export const MOCK_VEHICLES: Vehicle[] = [
  {
    id: 'v1',
    brand: 'Tesla',
    model: 'Model 3',
    trim: 'Long Range',
    batteryLevel: 50,
    chargingPort: 'Type-2, CCS-2',
    imageUrl: 'https://images.unsplash.com/photo-1536700503339-1e4b06520771?q=80&w=1000&auto=format&fit=crop'
  }
];

export const KERALA_DUMMY_STATIONS = [
  {
    id: 'kl-1',
    name: 'KSEB EV Hub Thrissur',
    address: 'Near KSEB Sub Station, Round South, Thrissur, Kerala 680001',
    lat: '10.5276',
    lng: '76.2144',
    distance: '28 km',
    cost: '14',
    openingHours: 'Open 24 Hours',
    source: 'sheet',
    numSlots: 4,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=800',
    connections: [
      { ConnectionType: { Title: 'CCS2 (Combined Charging)' }, PowerKW: 60, CurrentType: { Title: 'DC Fast Charge' }, StatusType: { IsOperational: true } },
      { ConnectionType: { Title: 'Type 2 (Mennekes)' }, PowerKW: 22, CurrentType: { Title: 'AC (Three-Phase)' }, StatusType: { IsOperational: true } },
    ],
    chargers: [
      { id: 'kl1-c1', name: 'DC Fast Charger 1', type: 'CCS2', capacity: '60KW', isAvailable: true },
      { id: 'kl1-c2', name: 'DC Fast Charger 2', type: 'CCS2', capacity: '60KW', isAvailable: false },
      { id: 'kl1-c3', name: 'AC Charger A', type: 'Type-2', capacity: '22KW', isAvailable: true },
      { id: 'kl1-c4', name: 'AC Charger B', type: 'Type-2', capacity: '22KW', isAvailable: true },
    ],
    attractions: ['Thrissur Town', 'Vadakkunnathan Temple', 'Parking'],
    coordinates: { lat: 10.5276, lng: 76.2144 },
    roadDistance: '28.3 km',
  },
  {
    id: 'kl-2',
    name: 'Tata Power EV Station Kochi',
    address: 'Marine Drive Promenade, Ernakulam, Kochi, Kerala 682031',
    lat: '9.9816',
    lng: '76.2726',
    distance: '86 km',
    cost: '16',
    openingHours: '06:00 AM – 11:00 PM',
    source: 'sheet',
    numSlots: 6,
    imageUrl: 'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?auto=format&fit=crop&q=80&w=800',
    connections: [
      { ConnectionType: { Title: 'CCS2 (Combined Charging)' }, PowerKW: 100, CurrentType: { Title: 'DC Fast Charge' }, StatusType: { IsOperational: true } },
      { ConnectionType: { Title: 'CHAdeMO' }, PowerKW: 50, CurrentType: { Title: 'DC Fast Charge' }, StatusType: { IsOperational: true } },
      { ConnectionType: { Title: 'Type 2 (Mennekes)' }, PowerKW: 22, CurrentType: { Title: 'AC (Three-Phase)' }, StatusType: { IsOperational: false } },
    ],
    chargers: [
      { id: 'kl2-c1', name: 'DC Ultra-Fast 1', type: 'CCS2', capacity: '100KW', isAvailable: true },
      { id: 'kl2-c2', name: 'DC Ultra-Fast 2', type: 'CCS2', capacity: '100KW', isAvailable: true },
      { id: 'kl2-c3', name: 'CHAdeMO Port', type: 'CHAdeMO', capacity: '50KW', isAvailable: true },
      { id: 'kl2-c4', name: 'AC Charger A', type: 'Type-2', capacity: '22KW', isAvailable: false },
    ],
    attractions: ['Marine Drive', 'Kochi Metro', 'Lulu Mall', 'WiFi'],
    coordinates: { lat: 9.9816, lng: 76.2726 },
    roadDistance: '87.2 km',
  },
  {
    id: 'kl-3',
    name: 'ChargeZone Palakkad',
    address: 'Big Bazaar Complex, Palakkad Town, Kerala 678001',
    lat: '10.7827',
    lng: '76.6554',
    distance: '53 km',
    cost: '13',
    openingHours: '07:00 AM – 10:00 PM',
    source: 'sheet',
    numSlots: 3,
    imageUrl: 'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?auto=format&fit=crop&q=80&w=800',
    connections: [
      { ConnectionType: { Title: 'CCS2 (Combined Charging)' }, PowerKW: 50, CurrentType: { Title: 'DC Fast Charge' }, StatusType: { IsOperational: true } },
      { ConnectionType: { Title: 'Type 2 (Mennekes)' }, PowerKW: 7.4, CurrentType: { Title: 'AC (Single-Phase)' }, StatusType: { IsOperational: true } },
    ],
    chargers: [
      { id: 'kl3-c1', name: 'DC Fast Charger', type: 'CCS2', capacity: '50KW', isAvailable: true },
      { id: 'kl3-c2', name: 'AC Charger A', type: 'Type-2', capacity: '7.4KW', isAvailable: true },
      { id: 'kl3-c3', name: 'AC Charger B', type: 'Type-2', capacity: '7.4KW', isAvailable: false },
    ],
    attractions: ['Big Bazaar', 'Palakkad Fort', 'Parking', 'WiFi'],
    coordinates: { lat: 10.7827, lng: 76.6554 },
    roadDistance: '54.1 km',
  },
  {
    id: 'kl-4',
    name: 'Statiq EV Station Kozhikode',
    address: 'SM Street, Kozhikode Beach Road, Kozhikode, Kerala 673001',
    lat: '11.2553',
    lng: '75.7765',
    distance: '74 km',
    cost: '15',
    openingHours: 'Open 24 Hours',
    source: 'sheet',
    numSlots: 5,
    imageUrl: 'https://images.unsplash.com/photo-1525609004556-c46c7d6cf023?auto=format&fit=crop&q=80&w=800',
    connections: [
      { ConnectionType: { Title: 'CCS2 (Combined Charging)' }, PowerKW: 60, CurrentType: { Title: 'DC Fast Charge' }, StatusType: { IsOperational: true } },
      { ConnectionType: { Title: 'Type 2 (Mennekes)' }, PowerKW: 22, CurrentType: { Title: 'AC (Three-Phase)' }, StatusType: { IsOperational: true } },
      { ConnectionType: { Title: 'Type 2 (Mennekes)' }, PowerKW: 22, CurrentType: { Title: 'AC (Three-Phase)' }, StatusType: { IsOperational: false } },
    ],
    chargers: [
      { id: 'kl4-c1', name: 'DC Fast Charger', type: 'CCS2', capacity: '60KW', isAvailable: true },
      { id: 'kl4-c2', name: 'AC Charger A', type: 'Type-2', capacity: '22KW', isAvailable: true },
      { id: 'kl4-c3', name: 'AC Charger B', type: 'Type-2', capacity: '22KW', isAvailable: false },
    ],
    attractions: ['Kozhikode Beach', 'SM Street', 'Cafe Coffee Day'],
    coordinates: { lat: 11.2553, lng: 75.7765 },
    roadDistance: '76.0 km',
  },
  {
    id: 'kl-5',
    name: 'Fortum EV Hub Malappuram',
    address: 'Near KSRTC Bus Stand, Malappuram Town, Kerala 676505',
    lat: '11.0510',
    lng: '76.0711',
    distance: '22 km',
    cost: '13',
    openingHours: '05:00 AM – 11:00 PM',
    source: 'sheet',
    numSlots: 3,
    imageUrl: 'https://images.unsplash.com/photo-1558981359-219d6364c9c8?auto=format&fit=crop&q=80&w=800',
    connections: [
      { ConnectionType: { Title: 'CCS2 (Combined Charging)' }, PowerKW: 50, CurrentType: { Title: 'DC Fast Charge' }, StatusType: { IsOperational: true } },
      { ConnectionType: { Title: 'Type 2 (Mennekes)' }, PowerKW: 22, CurrentType: { Title: 'AC (Three-Phase)' }, StatusType: { IsOperational: true } },
    ],
    chargers: [
      { id: 'kl5-c1', name: 'DC Fast Charger', type: 'CCS2', capacity: '50KW', isAvailable: true },
      { id: 'kl5-c2', name: 'AC Charger A', type: 'Type-2', capacity: '22KW', isAvailable: true },
      { id: 'kl5-c3', name: 'AC Charger B', type: 'Type-2', capacity: '22KW', isAvailable: false },
    ],
    attractions: ['KSRTC Stand', 'Malappuram Town', 'Parking'],
    coordinates: { lat: 11.0510, lng: 76.0711 },
    roadDistance: '23.4 km',
  },
  {
    id: 'kl-6',
    name: 'BPCL EV Point Guruvayur',
    address: 'BPCL Petrol Station, Guruvayur – Thrissur Road, Guruvayur, Kerala 680101',
    lat: '10.5937',
    lng: '76.0421',
    distance: '18 km',
    cost: '12',
    openingHours: 'Open 24 Hours',
    source: 'sheet',
    numSlots: 2,
    imageUrl: 'https://images.unsplash.com/photo-1561336313-0bd5e0b27ec8?auto=format&fit=crop&q=80&w=800',
    connections: [
      { ConnectionType: { Title: 'CCS2 (Combined Charging)' }, PowerKW: 30, CurrentType: { Title: 'DC Fast Charge' }, StatusType: { IsOperational: true } },
      { ConnectionType: { Title: 'Type 2 (Mennekes)' }, PowerKW: 7.4, CurrentType: { Title: 'AC (Single-Phase)' }, StatusType: { IsOperational: true } },
    ],
    chargers: [
      { id: 'kl6-c1', name: 'DC Charger', type: 'CCS2', capacity: '30KW', isAvailable: true },
      { id: 'kl6-c2', name: 'AC Charger', type: 'Type-2', capacity: '7.4KW', isAvailable: true },
    ],
    attractions: ['Guruvayur Temple', 'Devaswom Board', 'Parking'],
    coordinates: { lat: 10.5937, lng: 76.0421 },
    roadDistance: '19.1 km',
  },
  {
    id: 'kl-7',
    name: 'Ather Grid Kottayam',
    address: 'KK Road, Near Baker Junction, Kottayam, Kerala 686001',
    lat: '9.5916',
    lng: '76.5222',
    distance: '113 km',
    cost: '15',
    openingHours: '08:00 AM – 10:00 PM',
    source: 'sheet',
    numSlots: 4,
    imageUrl: 'https://images.unsplash.com/photo-1571055107559-3e67626fa8be?auto=format&fit=crop&q=80&w=800',
    connections: [
      { ConnectionType: { Title: 'Type 2 (Mennekes)' }, PowerKW: 22, CurrentType: { Title: 'AC (Three-Phase)' }, StatusType: { IsOperational: true } },
      { ConnectionType: { Title: 'CCS2 (Combined Charging)' }, PowerKW: 50, CurrentType: { Title: 'DC Fast Charge' }, StatusType: { IsOperational: true } },
    ],
    chargers: [
      { id: 'kl7-c1', name: 'DC Fast Charger', type: 'CCS2', capacity: '50KW', isAvailable: true },
      { id: 'kl7-c2', name: 'AC Charger A', type: 'Type-2', capacity: '22KW', isAvailable: true },
      { id: 'kl7-c3', name: 'AC Charger B', type: 'Type-2', capacity: '22KW', isAvailable: false },
      { id: 'kl7-c4', name: 'AC Charger C', type: 'Type-2', capacity: '22KW', isAvailable: true },
    ],
    attractions: ['Baker Junction', 'Kottayam Railway Station', 'Cafe'],
    coordinates: { lat: 9.5916, lng: 76.5222 },
    roadDistance: '115.7 km',
  },
  {
    id: 'kl-8',
    name: 'NTPC EV Station Thiruvananthapuram',
    address: 'Thampanoor, Near Central Station, Thiruvananthapuram, Kerala 695001',
    lat: '8.4875',
    lng: '76.9525',
    distance: '209 km',
    cost: '17',
    openingHours: 'Open 24 Hours',
    source: 'sheet',
    numSlots: 8,
    imageUrl: 'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?auto=format&fit=crop&q=80&w=800',
    connections: [
      { ConnectionType: { Title: 'CCS2 (Combined Charging)' }, PowerKW: 150, CurrentType: { Title: 'DC Ultra-Fast' }, StatusType: { IsOperational: true } },
      { ConnectionType: { Title: 'CHAdeMO' }, PowerKW: 50, CurrentType: { Title: 'DC Fast Charge' }, StatusType: { IsOperational: true } },
      { ConnectionType: { Title: 'Type 2 (Mennekes)' }, PowerKW: 22, CurrentType: { Title: 'AC (Three-Phase)' }, StatusType: { IsOperational: true } },
      { ConnectionType: { Title: 'Type 2 (Mennekes)' }, PowerKW: 22, CurrentType: { Title: 'AC (Three-Phase)' }, StatusType: { IsOperational: true } },
    ],
    chargers: [
      { id: 'kl8-c1', name: 'DC Ultra-Fast 1', type: 'CCS2', capacity: '150KW', isAvailable: true },
      { id: 'kl8-c2', name: 'DC Ultra-Fast 2', type: 'CCS2', capacity: '150KW', isAvailable: true },
      { id: 'kl8-c3', name: 'CHAdeMO Port', type: 'CHAdeMO', capacity: '50KW', isAvailable: false },
      { id: 'kl8-c4', name: 'AC Charger A', type: 'Type-2', capacity: '22KW', isAvailable: true },
    ],
    attractions: ['Central Station', 'Padmanabha Swamy Temple', 'Cafe', 'WiFi'],
    coordinates: { lat: 8.4875, lng: 76.9525 },
    roadDistance: '212.3 km',
  },
  {
    id: 'kl-9',
    name: 'EESL Charging Hub Kannur',
    address: 'Civil Station Road, Near Collectorate, Kannur, Kerala 670001',
    lat: '11.8745',
    lng: '75.3704',
    distance: '95 km',
    cost: '14',
    openingHours: '06:00 AM – 10:00 PM',
    source: 'sheet',
    numSlots: 4,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=800',
    connections: [
      { ConnectionType: { Title: 'CCS2 (Combined Charging)' }, PowerKW: 50, CurrentType: { Title: 'DC Fast Charge' }, StatusType: { IsOperational: true } },
      { ConnectionType: { Title: 'Type 2 (Mennekes)' }, PowerKW: 22, CurrentType: { Title: 'AC (Three-Phase)' }, StatusType: { IsOperational: true } },
    ],
    chargers: [
      { id: 'kl9-c1', name: 'DC Fast Charger', type: 'CCS2', capacity: '50KW', isAvailable: true },
      { id: 'kl9-c2', name: 'AC Charger A', type: 'Type-2', capacity: '22KW', isAvailable: true },
      { id: 'kl9-c3', name: 'AC Charger B', type: 'Type-2', capacity: '22KW', isAvailable: true },
      { id: 'kl9-c4', name: 'AC Charger C', type: 'Type-2', capacity: '22KW', isAvailable: false },
    ],
    attractions: ['Kannur Collectorate', 'Fort St. Angelo', 'Parking'],
    coordinates: { lat: 11.8745, lng: 75.3704 },
    roadDistance: '97.5 km',
  },
  {
    id: 'kl-10',
    name: 'SunFuel EV Tirur',
    address: 'Tirur Town Centre, NH 966, Tirur, Malappuram, Kerala 676101',
    lat: '10.9138',
    lng: '75.9216',
    distance: '11 km',
    cost: '12',
    openingHours: '07:00 AM – 09:00 PM',
    source: 'sheet',
    numSlots: 3,
    imageUrl: 'https://images.unsplash.com/photo-1525609004556-c46c7d6cf023?auto=format&fit=crop&q=80&w=800',
    connections: [
      { ConnectionType: { Title: 'Type 2 (Mennekes)' }, PowerKW: 22, CurrentType: { Title: 'AC (Three-Phase)' }, StatusType: { IsOperational: true } },
      { ConnectionType: { Title: 'CCS2 (Combined Charging)' }, PowerKW: 30, CurrentType: { Title: 'DC Fast Charge' }, StatusType: { IsOperational: true } },
    ],
    chargers: [
      { id: 'kl10-c1', name: 'DC Charger', type: 'CCS2', capacity: '30KW', isAvailable: true },
      { id: 'kl10-c2', name: 'AC Charger A', type: 'Type-2', capacity: '22KW', isAvailable: true },
      { id: 'kl10-c3', name: 'AC Charger B', type: 'Type-2', capacity: '22KW', isAvailable: false },
    ],
    attractions: ['Tirur Town', 'Malappuram Market', 'Parking'],
    coordinates: { lat: 10.9138, lng: 75.9216 },
    roadDistance: '12.3 km',
  },
  {
    id: 'kl-11',
    name: 'KSEB EV Hub Ponnani',
    address: 'Near KSEB Office, Ponnani Town, Malappuram, Kerala 679577',
    lat: '10.7756',
    lng: '75.9199',
    distance: '9 km',
    cost: '13',
    openingHours: 'Open 24 Hours',
    source: 'sheet',
    numSlots: 2,
    imageUrl: 'https://images.unsplash.com/photo-1561336313-0bd5e0b27ec8?auto=format&fit=crop&q=80&w=800',
    connections: [
      { ConnectionType: { Title: 'CCS2 (Combined Charging)' }, PowerKW: 50, CurrentType: { Title: 'DC Fast Charge' }, StatusType: { IsOperational: true } },
      { ConnectionType: { Title: 'Type 2 (Mennekes)' }, PowerKW: 7.4, CurrentType: { Title: 'AC (Single-Phase)' }, StatusType: { IsOperational: true } },
    ],
    chargers: [
      { id: 'kl11-c1', name: 'DC Fast Charger', type: 'CCS2', capacity: '50KW', isAvailable: true },
      { id: 'kl11-c2', name: 'AC Charger', type: 'Type-2', capacity: '7.4KW', isAvailable: true },
    ],
    attractions: ['Ponnani Beach', 'Jumaa Masjid', 'Parking'],
    coordinates: { lat: 10.7756, lng: 75.9199 },
    roadDistance: '10.2 km',
  },
  {
    id: 'kl-12',
    name: 'Charge+Zone Kuttipuram',
    address: 'NH 66 Service Road, Near Kuttipuram Bridge, Malappuram, Kerala 679571',
    lat: '10.8491',
    lng: '75.9877',
    distance: '2 km',
    cost: '12',
    openingHours: 'Open 24 Hours',
    source: 'sheet',
    numSlots: 4,
    imageUrl: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&q=80&w=800',
    connections: [
      { ConnectionType: { Title: 'CCS2 (Combined Charging)' }, PowerKW: 60, CurrentType: { Title: 'DC Fast Charge' }, StatusType: { IsOperational: true } },
      { ConnectionType: { Title: 'Type 2 (Mennekes)' }, PowerKW: 22, CurrentType: { Title: 'AC (Three-Phase)' }, StatusType: { IsOperational: true } },
      { ConnectionType: { Title: 'Type 1 (J1772)' }, PowerKW: 7.4, CurrentType: { Title: 'AC (Single-Phase)' }, StatusType: { IsOperational: true } },
    ],
    chargers: [
      { id: 'kl12-c1', name: 'DC Fast Charger', type: 'CCS2', capacity: '60KW', isAvailable: true },
      { id: 'kl12-c2', name: 'AC Charger A', type: 'Type-2', capacity: '22KW', isAvailable: true },
      { id: 'kl12-c3', name: 'AC Charger B', type: 'Type-2', capacity: '22KW', isAvailable: true },
      { id: 'kl12-c4', name: 'Slow AC Charger', type: 'Type-1', capacity: '7.4KW', isAvailable: false },
    ],
    attractions: ['Kuttipuram Town', 'NH 66 Highway', 'Restaurant', 'Parking'],
    coordinates: { lat: 10.8491, lng: 75.9877 },
    roadDistance: '2.1 km',
  },
];

export const ONBOARDING_SLIDES = [
  {
    title: "Get your smart life with smart bike",
    description: "The future of transportation is electric, and we're here to help you get there.",
    image: "https://images.unsplash.com/photo-1558981806-ec527fa84c39?q=80&w=1000&auto=format&fit=crop"
  },
  {
    title: "The perfect solution for long road trips",
    description: "The future of transportation is electric, and we're here to help you get there.",
    image: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?q=80&w=1000&auto=format&fit=crop"
  },
  {
    title: "We're here to help you power your journey",
    description: "The future of transportation is electric, and we're here to help you get there.",
    image: "https://images.unsplash.com/photo-1563986768609-322da13575f3?q=80&w=1000&auto=format&fit=crop"
  }
];